/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-06-18 12:30:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"/mainScript.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"he\" />\r\n");
      out.write("<title>Recommender Authors</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"mainContent\">\r\n");
      out.write("\t\t<h1>Recommendation Authors</h1>\r\n");
      out.write("\t\t<div id=\"search\">\r\n");
      out.write("\t\t\t<input id=\"searchText\" type=\"text\" /> <br />\r\n");
      out.write("\t\t\t<button id=\"searchButton\">Search</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</br>\r\n");
      out.write("\t\t</br>\r\n");
      out.write("\t\t<div id=tableResult>\r\n");
      out.write("\t\t\t<table style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th id=\"author0\" colspan=\"2\"></th>\r\n");
      out.write("\t\t\t\t\t\t<th id=\"author1\" colspan=\"2\"></th>\r\n");
      out.write("\t\t\t\t\t\t<th id=\"author2\" colspan=\"2\"></th>\r\n");
      out.write("\t\t\t\t\t\t<th id=\"author3\" colspan=\"2\"></th>\r\n");
      out.write("\t\t\t\t\t\t<th id=\"author4\" colspan=\"2\"></th>\r\n");
      out.write("\t\t\t\t\t\t<th id=\"author5\" colspan=\"2\"></th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"score0\" colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"score1\" colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"score2\" colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"score3\" colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"score4\" colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"score5\" colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic00\" nowrap></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic01\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic10\" nowrap></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic11\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic20\" nowrap></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic21\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic30\" nowrap></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic31\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic40\" nowrap></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic41\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic50\" nowrap></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"topic51\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"result\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
